### ISSUE TITLE
Kevin's home directory hardcoded into release file.

### ISSUE THREAD

**Issue by thariq-shanavas** [kevinconway/remouseable#14]
Hi,

Looks like the author's home directory is hard coded into the prebuilt release. Here's an error message I'm getting on Windows.

```
remouseable connected and running.
panic: EOF

goroutine 1 [running]:
main.main()
        C:/Users/kc/code/kevinconway/remouseable/main.go:188 +0x1e93
```

**Comment by kevinconway** [comment]
This is a feature of Go and not something I intended.

I think there are two things that would improve this. One is replacing use of `panic` in `main.go` with something like [log.Fatalf](https://golang.org/pkg/log/#Fatalf) which would give more control over the error message and suppress the stack trace that includes the build path. The other is to change the Makefile and README build instructions to use `go build -trimpath main.go` which should remove the build directory from the file metadata.

I'll keep this issue open as a reminder for the next release.
