### ISSUE TITLE
where are the pre-built binaries?

### ISSUE THREAD

**Issue by luigiannelli** [kevinconway/remouseable#16]
where are the pre-built binaries?

**Comment by xorbital** [comment]
Like most github projects, they can be found on the "Releases" page
As the [Readme says](https://github.com/kevinconway/remouseable#building):
> There are pre-built binaries attached to each release [...]

Releases: https://github.com/kevinconway/remouseable/releases

**Comment by luigiannelli** [comment]
Thank you! Sorry for my ignorance.

**Comment by kevinconway** [comment]
Thanks for the assist @xorbital
