### ISSUE TITLE
Improve name of binaries in the release tab

### ISSUE THREAD

**Issue by Naereen** [kevinconway/remouseable#17]
Hello there,
I just discovered your project yesterday, with a friend/colleague of mine.
It worked fine!! For Windows as well as on Ubuntu (GNU/Linux). Congrats and thanks :clap: for this nice project!

However, we found that the names of the binaries are very confusing, in the "release" tab.
Could you consider improving them? Here aremy suggestions:

- `linux` => `remouseable_linux.bin`
- `osx` => `remouseable_osx.bin`
- `windows.exe` => `remouseable_windows.exe`

Also, the documentation says nothing about the first steps:
1. go to the release page,
2. download the binary for your platform,
3. rename it, make it executable, store it somewhere smart (e.g. on Ubuntu, `~/.local/bin/remouseable_linux.bin`),
4. etc.

Thanks in advance, and kind regards from France. -- @Naereen

**Comment by kevinconway** [comment]
Thanks @Naereen! I'm glad the application is working for you and I appreciate the feedback.

If you have time, I'd like to get your feedback on https://github.com/kevinconway/remouseable/pull/18. I have attempted to document installation instructions for each operating system. Let me know if you think this makes things clearer and if you have other suggestions to improve the documentation.

**Comment by kevinconway** [comment]
I merged the README improvements. If that doesn't address your issue then please re-open the issue or create a new one.

**Comment by Naereen** [comment]
Great!
