### ISSUE TITLE
macOS Application wrapper using AppleScript

### ISSUE THREAD

**Issue by isaacwisdom** [kevinconway/remouseable#21]
Hi, amazing work making this tool! I just wanted to share some work I did with Applescript to make a wrapper for reMouseable so it works more like an application than a CLI tool. Maybe some other macOS users will find it useful!
https://github.com/isaacwisdom/reMouseableApp

**Comment by kevinconway** [comment]
I'm glad you're enjoying the tool and it's working well for you. I'm happy to add your project to the README so other folks can find it. How does https://github.com/kevinconway/remouseable/pull/22 sound?

**Comment by isaacwisdom** [comment]
Looks good! Again, awesome tool.

**Comment by kevinconway** [comment]
Merged! You should see the link in the README now.
