### ISSUE TITLE
issue connecting on arch

### ISSUE THREAD

**Issue by Memylicious** [kevinconway/remouseable#25]
when i try to connect it doesnt seem to work, it outputs this error after around 2 mins sitting silent: 

     panic: dial tcp 10.11.99.1:22: connect: connection timed out

     goroutine 1 [running]:
     main.main()

the command i use is, ./remouseable --event-file /dev/input/event1 --ssh-ip="10.11.99.1:22" --ssh-password="(the password)", and i have been using it for a while and it has worked, but just today i switched to arch linux and it decided to stop working. i tried installing all the things for it to build but that didnt seem to help, any ideas? (also yes it is connected, checked through ip link or whatever it is)

**Comment by ddvk** [comment]
have you installed a network manager? is the device recognized as a network device `ip link`, `dmesg`?

**Comment by Memylicious** [comment]
> have you installed a network manager? is the device recognized as a network device `ip link`, `dmesg`?

im not sure where to check exactly for it being a network device, but i do have a network manager and when i do ip link this is what shows up "enp1s0f0u2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 1000 link/ether (the ip thing, not sure if i can show this) brd ff:ff:ff:ff:ff:ff"

**Comment by Memylicious** [comment]
just bumping this, still haven't figured anything out...

**Comment by kevinconway** [comment]
I don't have much to add, unfortunately. Maybe https://bbs.archlinux.org/viewtopic.php?id=241144 has some decent leads for you?

**Comment by Memylicious** [comment]
> I don't have much to add, unfortunately. Maybe https://bbs.archlinux.org/viewtopic.php?id=241144 has some decent leads for you?

thanks, ill look through it!

**Comment by Memylicious** [comment]
> I don't have much to add, unfortunately. Maybe https://bbs.archlinux.org/viewtopic.php?id=241144 has some decent leads for you?

thank you so much, copied and pasted some things from that thread and the following one and its working all fine just like before, for people who are coming here looking for an answer to this issue, i dont know which ones exactly fixed it, but try doing "sudo ip link set up (the name of your tablet found from ip link)" then "sudo dhclient (the name of the tablet found from ip link)" i think those were the commands that fixed it, if those didnt work then it was one of the things from the first thread.
