### ISSUE TITLE
Bumping that the home address problem is still an issue

### ISSUE THREAD

**Issue by cyanomys** [kevinconway/remouseable#27]
![image](https://user-images.githubusercontent.com/63557988/134829275-6bdaa6f9-6ec0-4878-a513-1eed453aed73.png)

**Comment by kevinconway** [comment]
I'm aware it's still an issue. The app _does_ work on Windows, though, if you provide the `--ssh-password` option. There's a [section in the README](https://github.com/kevinconway/remouseable#getting-panic-dial-unix-missing-address-on-windows) with instructions for connecting while using Windows and handling this specific error you're showing. There's also [an issue](https://github.com/kevinconway/remouseable/issues/10) open with suggestions on how someone can add SSH support for windows that doesn't require the root password of the device.
