### ISSUE TITLE
Question: What app should be foreground on the tablet?

### ISSUE THREAD

**Issue by ruswerner** [kevinconway/remouseable#29]
This app works great (aside from not being able to choose the monitor to use), however I'm not sure what app/UI screen to bring up on the reMarkable tablet to avoid tapping on things that cause problems. Is there a "blank screen" app somewhere that can be launched on the tablet so it's just empty?

Cheers

**Comment by kevinconway** [comment]
I use the quick sheets feature from the home screen to get a blank sheet. After drawing I either save a copy of the sheet for reference or erase it. If you hide the tool-bar using the arrow in the upper left-hand corner then it removes just about everything that could be problematic to click on.
