### ISSUE TITLE
panic: ssh: handshake failed: EOF

### ISSUE THREAD

**Issue by gmontamat** [kevinconway/remouseable#33]
Hi, I'm getting this error when trying out my remarkable2 both on MacOS Monterrey and Ubuntu 22.04.
```
$ ./remousable --ssh-password="myPass" --event-file="/dev/input/event1"
panic: ssh: handshake failed: EOF

goroutine 1 [running]:
main.main()
	/mnt/c/Users/kc/code/kevinconway/remouseable/main.go:88 +0x1fb3
```
ssh is working fine on both OSs. My remarkable OS version is 3.0.4.1305, could it be an incompatibility issue with the new 3.x release?

edit: https://github.com/Evidlo/remarkable_mouse works fine so I guess it's related to golang's ssh package

**Comment by cyb3n3tic** [comment]
For what it is worth I'm seeing the same issue running 3.1.1.1415

**Comment by troyrollo** [comment]
The libraries used by remouseable require a server RSA key and/or DSS key. Version 3 of the Remarkable does not create or use one. You can set it up yourself by doing the following on the Remarkable as root:

Run the following commands:
```
dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key
dropbearkey -t dss -f /etc/dropbear/dropbear_dss_host_key
```

edit /etc/default/dropbear and change the value of DROPBEAR_EXTRA_ARGS as follows:

```
DROPBEAR_EXTRA_ARGS=" -B -r /etc/dropbear/dropbear_rsa_host_key -d /etc/dropbear/dropbear_dss_host_key "
```
There is no need to reboot or restart any service after doing this, and you should not do so until you have verified that at least SSH still works for a new connection.

**Comment by danielzuegner** [comment]
You are my savior! Worked like a charm. Thanks!

**Comment by bederman** [comment]
@troyrollo Can you explain your answer in more detail? I don't have `dropbearkey` installed and am unfamiliar with it. It seems like there's some assumed setup here to leverage this. I don't have an `/etc/default/dropbear` on macOS.

**Comment by jlazovskis** [comment]
@bederman First ssh into your remarkable with `ssh root@10.11.99.1` and then run the two `dropbearkey` commands inside your remarkable. The file `/etc/default/dropbear` in your remarkable needs to be edited as described, which you can do with your favorite text editor. For example, calling `vi /etc/default/dropbear` during the ssh session inside your remarkable will open up the file in `vi`, so then you can replace the line with the one given.

**Comment by bederman** [comment]
@jlazovskis My ssh doesn't have `dropbearkey` installed. What's the recommended way to do this?

**Comment by calpals** [comment]
@jlazovskis after opening the file in `vi`, I can't seem to edit any of the text. I can paste `DROPBEAR_EXTRA_ARGS=" -B -r /etc/dropbear/dropbear_rsa_host_key -d /etc/dropbear/dropbear_dss_host_key "`, but it doesn't replace the already existing `4 DROPBEAR_EXTRA_ARGS=" -B"` line. I can't delete anything in `vi`. 

Also, how do I save the changes to the file (assuming I eventually figure out how to correctly make the edits)?

EDIT: I figured out how to edit the file. This article helped if anyone is having similar issues (https://www.keycdn.com/blog/vim-commands)

**Comment by Sheap** [comment]
This worked for me, however, vi wasn't working properly (I got many errors regarding the .vimrc file, and couldn't interact with the text. This was a config issue, not the normal "how does vim work" pebcak (granted it could be (probably is) a different flavour of pebcak))

but the following sed command did the job for me:
`sed -i -- 's:DROPBEAR_EXTRA_ARGS=" -B":DROPBEAR_EXTRA_ARGS=" -B -r /etc/dropbear/dropbear_rsa_host_key -d /etc/dropbear_dss_host_key ":' /etc/default/dropbear`

**Comment by kevinconway** [comment]
Fixed by https://github.com/kevinconway/remouseable/releases/tag/v0.5.0.

@troyrollo was exactly right with the issue and their workaround should continue to work for anyone using it. The latest patch of the project fixes SSH so you shouldn't have to create a new key on the tablet. If a future software update on the tablet changes the SSH key type on the device again then you'll get the same error and should be able to use the same workaround to get by it.
