### ISSUE TITLE
panic: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

### ISSUE THREAD

**Issue by calpals** [kevinconway/remouseable#39]
Using a ReMarkable 2, this is the code I have in my terminal:
``` remouseable --ssh-password=“mypass --event-file="/dev/input/event1"

panic: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

goroutine 1 [running]:
main.main()
	/Users/kevinconway/code/kconwayinvision/remouseable/main.go:88 +0x1f85
```

I was originally getting the error `panic: ssh: handshake failed: EOF`, but fixed it thanks to [this thread](https://github.com/kevinconway/remouseable/issues/33). How do I stop it from panicking?

**Comment by mitasovr** [comment]
The same error for me, any updates?

**Comment by kevinconway** [comment]
SSH issues are fixed in https://github.com/kevinconway/remouseable/releases/tag/v0.5.0.
