### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by yin-dra** [kevinconway/remouseable#40]
Despite remouseable reporting "connected and running," there is no cursor movement on the Mac and no indication of tablet mode on the Remarkable. I have ensured the SSH connection is stable and verified input events are being generated on the Remarkable.

**System Information:**

Mac OS Version: 14.4
Remarkable Version: 3.11.2.5
Remouseable Version: Mar 9, 2021
Network Configuration: Both devices are on the same local network

**Additional Information:**

SSH authentication: Password-based
Permissions: Verified correct permissions for key files and input event file
Reboot: Rebooted both devices multiple times
Logs: No specific error messages observed in the console
Questions:

Are there any additional configuration steps required to enable cursor movement and tablet mode?
Could there be an issue with the specific version of remouseable or the Remarkable software?
Are there any known compatibility issues with Mac OS version [Your Mac OS version]?

**Comment by kevinconway** [comment]
The most common OSX issue is this: https://github.com/kevinconway/remouseable?tab=readme-ov-file#osx-privacy-settings. It doesn't work on modern OSX unless you give it extra permissions.
