### ISSUE TITLE
Unable to "install" on Windows

### ISSUE THREAD

**Issue by arturbecker** [kevinconway/remouseable#7]
Hey Kevin, thanks for your work on this project.
I am currently unable to use it in Windows, probably due to a lack of technical know-how (I'd rather use Linux, but it's on Windows that I have the most use for the tablet features...)
Here's what I get when trying to run the .exe, and then remouseable:

```
C:\Users\artur\Downloads>windows.exe
panic: dial unix: missing address

goroutine 1 [running]:
main.main()
        /home/travis/gopath/src/github.com/kevinconway/remouseable/main.go:68 +0x135d
```
```
C:\Users\artur\Downloads>remouseable
'remouseable' is not recognized as an internal or external command,
operable program or batch file.

```

**Comment by kevinconway** [comment]
This happens on Windows when there is no SSH password provided when running the command. You'll need to either pass in your password with `windows.exe --ssh-password="MYPASSWORD"` or `windows.exe --ssh-password="-"` which will trigger a password prompt if you prefer to not have the password in your terminal's history.

Instructions for finding your tablet's password is here: https://github.com/kevinconway/remouseable#usage. Also, be aware that if you have a remarkable 2 tablet then you also need to provide a second option described here: https://github.com/kevinconway/remouseable#remarkable-2-tablets.

I'm going to close the issue but feel free to re-open if that doesn't fix things for you.

**Comment by loom7** [comment]
Hey, i have the same problem, but using a ssh-password on windows:
(Worked once, then i closed the cmd nad then it showed this, also after reboot of the tablet and the pc)

```
remouseable.exe --ssh-ip="192.168.254.61:22 --ssh-password="therootpassword"
panic: dial unix: missing address

goroutine 1 [running]:
main.main()
        /home/travis/gopath/src/github.com/kevinconway/remouseable/main.go:68 +0x135d
```
or
```
remouseable0.4.exe --ssh-ip="192.168.254.61:22 --ssh-password="therootpassword"
panic: dial unix: missing address

goroutine 1 [running]:
main.main()
        C:/Users/kc/code/kevinconway/remouseable/main.go:71 +0x1fc5`
```
with ver. 0.4
